
name: Chrome headless

on: push

jobs:
  chrome-headless:
    runs-on: ubuntu-20.04(ubuntu-latest)
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Headless Chrome
        uses: cypress-io/github-action@v5
        timeout-minutes: 10
        with:
          build: npm run build
          start: npm start
          browser: chrome