name: Continuous Deployment

on:
  push:
    branches: [ master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5 
        with:
          record: false
          config-file: ../../cypress.config.js
          browser: chrome
          headed: true
          start: npm start
          wait-on: 'http://localhost:3000'
          command: npm run e2e:ci