name: Continuous Deployment

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@master
        - uses: cypress-io/github-action@master
          with:
            build: npm run build:prod
            start: npm start