name: Continuous Integration

on:
  pull_request:
    branches: [ master ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@master
        - uses: cypress-io/github-action@master
          with:
            build: npm run build:prod
            start: npm run start


